version: '3.7'

services:
  postgres:
    container_name: dev-postgres
    image: bitnami/postgresql:14.1.0-debian-10-r31
    restart: unless-stopped
    environment:
      - POSTGRESQL_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_dev_data:/bitnami/postgresql
      - ./scripts/postgres/00-init.sql:/docker-entrypoint-initdb.d/00-init.sql

  api:
    image: alpine/socat
    container_name: dev-api-proxy
    restart: unless-stopped
    command: tcp-listen:3100,fork tcp:host.docker.internal:3100

volumes:
  postgres_dev_data:
